### ISSUE TITLE
Split quotes into different files

### ISSUE THREAD

**Issue by bchurchill** [bchurchill/bahai-quotes#3]
While the "source" of a quote is the original text it appears in, there are many ways a quote might find its way into this collection.  For example, an individual might add a miscellaneous quote they like, or a developer might scrape a particular website.  We would like for users to be able to choose which one(s) they use for their applications; therefore, I'm planning on splitting up the big json file into smaller ones based on the source of the quotes.  Later, we'll provide scripts for combining them and writing to different formats.

**Comment by bchurchill** [comment]
> "Not sure how valuable it'll be to create a separate page for the quotes. I think a better solution would be creating a platform that checks whether a quote exists already - and if it doesn't, it'll create a new node for the new quote added."

There are two reasons that I'm suggesting this, and both boil down to simplicity which is the major goal.  

First, it makes it easier to add new collections of quotes.  No worrying about having to run a script to merge with existing ones.  The script could be really hard to write because of identical quotes from different sources, or one version that's slightly longer than another, etc.  Also, if two people wanted to add their quotes at the same time, there'd be no chance of merge conflict.

Second, it makes it easier to pick something out.  Like, if someone made a collection of quotes from Ruhi 1, the 'source' metadata would reference original texts like "Epistle to the Son of the Wolf".  So, it would make it easier to _just_ get the Ruhi 1-sourced quotes.  Similarly for your collection from Lights of Guidance, for example.  It also reduces need for centralized quality control: if someone wants to submit quotes, they can by making a new file.  And, if people don't like them they don't need to use them.

**Comment by adibbehjat** [comment]
That makes much more sense. You're right :+1: 

Will you create the new folders?

And what standard do you prefer on utilizing. While my data set has tags, it would be more ideal if you set the standard

**Comment by bchurchill** [comment]
I think tags is a great idea.  We should use those.  The format you have is fine.  Another advantage of individual files is that if some are missing tags (like my old ones), that's okay.

**Comment by bchurchill** [comment]
Closed in 465236f36ea.

**Comment by bchurchill** [comment]
Also, feel free to add other metadata fields, like "section"/"subsection"/"subsubsection".  I think as long as each individual source is consistent, it's okay.  There's now a generate.rb script that takes all the files in /sources/ and aggregates them together.  Any new files should work with this script (which can be modified if needed).
